### ISSUE TITLE
Doubt regarding facebook integration for windows phone 8.1 silverlight app?

### ISSUE THREAD

**Issue by sureshmarepalli** [facebook-csharp-sdk/facebook-winclient-sdk#59] opened 2015-02-03 05:01 UTC
Hi,

I am developing a windows phone 8.1 silverlight application . For my application I integrated the facebook login. For this facebook integration I used the login with facebook app method.

My doubt is after getting the app id from the dev center , I updated the appid at developers.facebook.com , wmmanifest.xml (In extensions protocol (msft-appid without dashes)) . Or do I need to change the product id in the place holder also , I tried to change the productid also but I am getting error like some signature is wrong try with different signature. I am confused how to do it .

Any help,

Thanks...

**Comment by sanjeevdwivedi** [comment] 2015-02-12 09:09
Look at the documentation for silverlight apps or load the Facebook-WP8.sln from the github repository which has a full sample. Closing since this is not a bug. If you need help coding this up, please open a discussion on stackoverflow.

**Closed by sanjeevdwivedi** 2015-02-12 09:09 UTC
